name: Run Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ 7.2, 7.3 ]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Update apt
        run: sudo apt-get update

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.8.0
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files/
          key: composer

      - name: Install dependencies
        run: |
          composer update --no-interaction --no-progress --prefer-dist --prefer-stable

      - name: Run Tests
        run: composer test
