name: Run Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ 7.2, 7.3, 7.4, 8.0 ]
        stability: [ prefer-stable, prefer-lowest ]

    name: PHP ${{ matrix.php }} [${{ matrix.stability }}]

    steps:
      - name: Update apt
        run: sudo apt-get update

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.8.0
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files/
          key: composer

      - name: Set minimum sub-dependencies version
        run: |
          composer require sebastian/comparator:^1.2.3 phpspec/prophecy:^1.9.1 --no-interaction --no-progress \
            --prefer-dist --${{ matrix.stability }}
        if: ${{ matrix.php >= 7.2 && matrix.php < 8 && matrix.stability == 'prefer-lowest' }}

      - name: Install dependencies
        run: |
          composer update --no-interaction --no-progress --prefer-dist --${{ matrix.stability }}

      - name: Run Tests
        run: composer test
